---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-health-monitor-config
  namespace: kube-system
data:
  config.yaml: |+
    checkers:
      - name: "internal-coredns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "kubernetes.default.svc.cluster.local"
      - name: "external-coredns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "mcr.microsoft.com"
      - name: "internal-localdns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "kubernetes.default.svc.cluster.local"
          checkLocalDNS: true
      - name: "external-localdns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "mcr.microsoft.com"
          checkLocalDNS: true
      - name: "pod-startup"
        type: "podStartup"
        interval: "1m"
        timeout: "30s"
        podStartupConfig:
          syntheticPodNamespace: "kube-system"
          syntheticPodLabelKey: "kubernetes.azure.com/cluster-health-monitor-checker-synthetic"
          syntheticPodStartupTimeout: "5s"
          maxSyntheticPods: 10
        
