---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-health-monitor
  namespace: kube-system
  labels:
    app: cluster-health-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-health-monitor
  template:
    metadata:
      labels:
        app: cluster-health-monitor
    spec:
      serviceAccountName: cluster-health-monitor
      containers:
        - name: cluster-health-monitor
          # TODO: Update the image to the latest version.
          image: mcr.microsoft.com/aks/cluster-health-monitor/cluster-health-monitor:v0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9800
              name: metrics
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cluster-health-monitor
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config-volume
          configMap:
            name: cluster-health-monitor-config
